### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by pronebird** [jacobp100/babel-plugin-swift-blocks#1]
```
failed with "Cannot find module 'babylon/lib/parser'"
```

**Comment by jacobp100** [comment]
Sorry, babel switched over to a flat bundle, so this can no longer work.

**Comment by pronebird** [comment]
@jacobp100 it is possible to fix it? I like the plugin you've made :)

**Comment by jacobp100** [comment]
Unlikely! See the last comment of https://github.com/babel/babylon/pull/190 😉

**Comment by pronebird** [comment]
Hmm ok :) I'll look into plugin handbook instead then. I found your medium post quite helpful but seems that the way plugins are built has changed since then :)
